language: elm
script: make release

before_install:
  - curl https://nixos.org/nix/install | sh
  - source ~/.nix-profile/etc/profile.d/nix.sh
  - elm make src/Main.elm --output /dev/null

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local-dir: app
  on:
    branch: master